
CREATE TABLE RELATORIO_REL (
    id           INTEGER  PRIMARY KEY AUTOINCREMENT,
    REL_CODIGO   INTEGER (10)  UNIQUE,
    REL_NOME     VARCHAR (255),
    REL_DRIVE    VARCHAR (255),
    REL_HOSTNAME VARCHAR (255),
    REL_DATABASE VARCHAR (255),
    REL_USERNAME VARCHAR (255),
    REL_PASSWORD VARCHAR (255) 
);

CREATE TABLE RELCAMPO_RCP (
    id              integer  PRIMARY KEY AUTOINCREMENT,
    RCP_CODIGO      VARCHAR (40)  UNIQUE,
    RCP_NOME        VARCHAR (255),
    RCP_TPPARAMETRO VARCHAR (20),
    RCP_TPCAMPO     VARCHAR (20),
    RCP_FORMATO     VARCHAR (20),
    RCP_VLRDEFAULT  VARCHAR (20),
    RCP_VISIVEL     CHAR (1),
    RCP_TAMANHO     INTEGER (255),
    RCP_ORDEM       INTEGER (100),
    RELCONSULTA_RCL VARCHAR (32)  REFERENCES RELATORIO_REL (id) ON DELETE CASCADE
);


CREATE TABLE RELCONSULTA_RCL (
    id             integer  PRIMARY KEY AUTOINCREMENT,
    RCL_DESCRICAO VARCHAR (255),
    RCL_CONSULTA  VARCHAR (4000),
    RELATORIO     VARCHAR (32)   REFERENCES RELATORIO_REL (id) ON DELETE CASCADE,
    RCL_MODELO    VARCHAR (100) 
);
